apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: customservices.fbruandrade.myfirstoperator
spec:
    group: fbruandrade.myfirstoperator
    version: v1
    scope: Namespaced
    names:
        plural: customservices
        singular: customservice
        kind: CustomService
        shortNames:
            - csvc